@startuml

enum Suit {
    - shortName: String
    + show(): String
}

enum Rank{
    - rank: String
    - points: ArrayList<Integer>
    + getPoints(): ArrayList<Integer>
    + show(): String
}

class Card {
    - suit: Suit
    - rank: Rank
    + getPoints(): ArrayList<Integer>
    + show(): String
}

Card o-- Suit
Card o-- Rank

class Deck {
    - cards: ArrayList<Card>
    - currentCardIndex: int
    + nextCard(): Card
    + shuffle()
}

class BlackjackSolitaireLine {
    - cards: ArrayList<Card>
    - threshold: int
    + getPoints(): int
    + getLength(): int
}

class BlackjackSolitaireTable {
    - cells: Card[]
    - getNumberOfFreeDiscardCells(): int
    - getCardNameByIndex(): String
    - createArrayListFromCellsIndexes(): ArrayList<Card>
    + isFull(): boolean
    + putCardToCell()
    + getBlackjackSolitaireLines(): BlackjackSolitaireLine[]
    + show(): String
}

class ScoreResolver {
    + CalculateScoreForLine(): int
}

class BlackjackSolitaire {
    - getFinalScoreMessage(): String
    + play()
}

class BlackjackSolitaireRunner{
    + main()
}

BlackjackSolitaireRunner ..> BlackjackSolitaire

BlackjackSolitaireTable ..> BlackjackSolitaireLine
BlackjackSolitaireTable ..> Card

BlackjackSolitaire ..> ScoreResolver
BlackjackSolitaire ..> BlackjackSolitaireTable
BlackjackSolitaire ..> Deck
BlackjackSolitaire ..> Card

ScoreResolver ..> BlackjackSolitaireLine

BlackjackSolitaireLine o-- Card

Deck o-- Card
Deck ..> Suit
Deck ..> Rank
@enduml
